# Generated by Django 3.1.3 on 2020-12-11 02:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='Customer ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('was_created_successfully', models.BooleanField(default=False)),
                ('customer_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethodToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='Token ID')),
                ('payment_method_token', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('bin', models.CharField(blank=True, max_length=10, null=True)),
                ('card_last_digits', models.CharField(blank=True, max_length=10, null=True)),
                ('cardholder_name', models.CharField(blank=True, max_length=50, null=True)),
                ('expiration_month', models.CharField(blank=True, max_length=5, null=True)),
                ('expiration_year', models.CharField(blank=True, max_length=5, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('paid_through_date', models.DateField(blank=True, null=True)),
                ('billing_day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('first_billing_date', models.DateField(blank=True, null=True)),
                ('billing_period_start_date', models.DateField(blank=True, null=True)),
                ('billing_period_end_date', models.DateField(blank=True, null=True)),
                ('current_billing_cycle', models.PositiveIntegerField(blank=True, null=True)),
                ('days_past_due', models.PositiveIntegerField(blank=True, null=True)),
                ('next_billing_date', models.DateField(blank=True, null=True)),
                ('failure_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bt_subscription_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subscription ID')),
                ('bt_payment_method_token', models.CharField(blank=True, max_length=255, null=True)),
                ('bt_plan_id', models.CharField(blank=True, max_length=255, null=True)),
                ('bt_price', models.FloatField(blank=True, null=True)),
                ('bt_status', models.CharField(blank=True, max_length=50, null=True)),
                ('trial_duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('trial_duration_unit', models.CharField(blank=True, max_length=5, null=True)),
                ('trial_period', models.BooleanField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='payments.customer')),
                ('payment_method_token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='payments.paymentmethodtoken')),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.coursepackage')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('bt_transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction ID')),
                ('was_success', models.BooleanField(default=False)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_amount', models.FloatField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.customer')),
                ('on_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.subscription')),
                ('payment_method_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.paymentmethodtoken')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='Subscription Status ID')),
                ('is_in_trial', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACTIVE', 'ACTIVE'), ('PAST_DUE', 'PAST_DUE'), ('CANCELED', 'CANCELED'), ('EXPIRED', 'EXPIRED')], max_length=20)),
                ('was_charged_successfully', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='payments.subscription')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_method_token',
            field=models.ManyToManyField(blank=True, related_name='customers', to='payments.PaymentMethodToken'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='accounts.userprofile'),
        ),
    ]
