# Generated by Django 3.1.3 on 2020-12-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20201217_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethodtoken',
            name='type',
            field=models.CharField(blank=True, choices=[('CreditCard', 'CreditCard'), ('PayPalAccount', 'PayPalAccount')], default='CreditCard', max_length=20, null=True),
        ),
    ]
