# Generated by Django 3.1.3 on 2020-12-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentmethodtoken_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethodtoken',
            name='bin',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethodtoken',
            name='card_last_digits',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethodtoken',
            name='cardholder_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethodtoken',
            name='expiration_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethodtoken',
            name='expiration_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethodtoken',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
