# Generated by Django 3.1.3 on 2020-12-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20201204_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethodtoken',
            name='bin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethodtoken',
            name='card_last_digits',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethodtoken',
            name='expiration_month',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethodtoken',
            name='expiration_year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
