# Generated by Django 3.1.3 on 2020-12-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20201231_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_payment_error_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_payment_has_error',
            field=models.BooleanField(default=False),
        ),
    ]
