# Generated by Django 3.1.3 on 2021-01-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20201231_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethodtoken',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethodtoken',
            name='payment_method_token',
            field=models.CharField(help_text='Fingerprint for Stripe', max_length=100),
        ),
    ]
