# Generated by Django 3.1.3 on 2021-01-22 17:59

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_customer_is_attempt'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
