# Generated by Django 3.1.3 on 2021-01-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20210122_1759'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment_method_token',
            field=models.ManyToManyField(blank=True, related_name='customers', to='payments.PaymentMethodToken', verbose_name='Cards'),
        ),
    ]
