# Generated by Django 3.1.3 on 2022-05-31 18:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_auto_20210122_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(default=core.models.get_guid, editable=False, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('payment_intent_id', models.CharField(max_length=255)),
                ('charge_id', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('amount', models.PositiveIntegerField()),
                ('payment_intent_json_object_before', models.TextField()),
                ('payment_intent_json_object_after', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
