# Generated by Django 3.1.3 on 2020-11-29 14:08

from django.db import migrations, models
import django.db.models.deletion
import e_learning.fields
import mt_utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_userprofile'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=255)),
                ('description_box', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoursePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.FloatField(default=0.0)),
                ('description_box', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoursePlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseVideoMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('time', models.FloatField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=255, verbose_name='Title')),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description_box', models.TextField(blank=True, null=True)),
                ('video', e_learning.fields.VideoField(upload_to=mt_utils.get_course_video_path)),
                ('thumbnail', models.ImageField(upload_to=mt_utils.get_course_video_thumbnail_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_videos', to='e_learning.coursecategory')),
                ('comments', models.ManyToManyField(blank=True, related_name='course_video_comments', to='comment.Thread')),
                ('instructors', models.ManyToManyField(blank=True, related_name='course_videos', to='accounts.Member')),
                ('marks', models.ManyToManyField(blank=True, related_name='course_videos', to='e_learning.CourseVideoMark')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_videos', to='e_learning.coursepackage')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_videos', to='e_learning.courseplaylist')),
                ('views', models.ManyToManyField(blank=True, related_name='viewed_course_videos', to='accounts.UserProfile')),
            ],
        ),
    ]
