# Generated by Django 3.1.3 on 2020-11-29 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevideo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_videos', to='e_learning.coursecategory'),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_videos', to='e_learning.coursepackage'),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_videos', to='e_learning.courseplaylist'),
        ),
    ]
