# Generated by Django 3.1.3 on 2020-11-29 16:37

from django.db import migrations, models
import django.db.models.deletion
import mt_utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201129_1637'),
        ('e_learning', '0002_auto_20201129_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseVideoHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('at_time', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='coursevideo',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='coursevideo',
            name='views',
        ),
        migrations.AddField(
            model_name='courseplaylist',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='e_learning.CourseVideo'),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='cc',
            field=models.FileField(blank=True, null=True, upload_to=mt_utils.get_course_video_cc_path),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_videos', to='accounts.coursepackage'),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=mt_utils.get_course_video_thumbnail_path),
        ),
        migrations.DeleteModel(
            name='CoursePackage',
        ),
        migrations.AddField(
            model_name='coursevideohistory',
            name='course_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='e_learning.coursevideo'),
        ),
        migrations.AddField(
            model_name='coursevideohistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_video_history', to='accounts.userprofile'),
        ),
    ]
