# Generated by Django 3.1.3 on 2020-11-29 18:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201129_1637'),
        ('e_learning', '0003_auto_20201129_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchLetterPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch_letter_videos', to='accounts.userprofile')),
                ('videos', models.ManyToManyField(blank=True, to='e_learning.CourseVideo')),
            ],
        ),
    ]
