# Generated by Django 3.1.3 on 2020-11-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0004_watchletterplaylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='thumbs_down',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='thumbs_up',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
