# Generated by Django 3.1.3 on 2020-11-30 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201129_1637'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e_learning', '0005_auto_20201129_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursevideo',
            name='thumbs_down',
        ),
        migrations.RemoveField(
            model_name='coursevideo',
            name='thumbs_up',
        ),
        migrations.CreateModel(
            name='ThumbUpUserVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumb_ups', to='e_learning.coursevideo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumb_up_videos', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('message', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_comments', to=settings.AUTH_USER_MODEL)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='course_video_comments', to='e_learning.Comment'),
        ),
    ]
