# Generated by Django 3.1.3 on 2020-12-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0008_auto_20201202_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseplaylist',
            name='description_box',
            field=models.TextField(blank=True, null=True),
        ),
    ]
