# Generated by Django 3.1.3 on 2020-12-10 16:51

from django.db import migrations, models
import e_learning.fields
import mt_utils


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0011_auto_20201208_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='upload_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='video',
            field=e_learning.fields.VideoField(blank=True, null=True, upload_to=mt_utils.get_course_video_path),
        ),
    ]
