# Generated by Django 3.1.3 on 2020-12-10 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0012_auto_20201210_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursevideo',
            name='upload_id',
        ),
    ]
