# Generated by Django 4.0.4 on 2022-05-29 07:01

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(default=core.models.get_guid, editable=False, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(default=core.models.get_guid, editable=False, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('starts', models.DateTimeField()),
                ('ends', models.DateTimeField()),
                ('price', models.FloatField()),
                ('discount_percentage_off', models.FloatField(default=0)),
                ('discount_amount_off', models.FloatField(default=0)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='campaign.campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(default=core.models.get_guid, editable=False, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], max_length=255)),
                ('date_of_birth', models.DateField()),
                ('parent_names', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=255)),
                ('parent_email', models.EmailField(max_length=254)),
                ('player_email', models.EmailField(max_length=254)),
                ('health_card_number', models.CharField(max_length=255)),
                ('allergies', models.CharField(max_length=255)),
                ('injuries', models.CharField(max_length=255)),
                ('emergency_contact_number', models.CharField(max_length=255)),
                ('campaign_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='campaign.campaignpackage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
