# Generated by Django 4.0.4 on 2022-05-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_campaignpackage_discount_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignsubscriber',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
