# Generated by Django 3.1.3 on 2022-05-31 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_auto_20220530_2316'),
        ('campaign', '0005_auto_20220531_1859'),
    ]

    operations = [
    ]
