# Generated by Django 3.1.3 on 2021-01-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='customer_id',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='webhook',
            name='object_id',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
