# Generated by Django 3.1.3 on 2020-11-25 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('INSTRUCTOR', 'INSTRUCTOR'), ('CEO', 'CEO'), ('POSTER', 'POSTER'), ('MEMBER', 'MEMBER')], max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
