# Generated by Django 3.1.3 on 2020-12-14 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mt_utils
import phonenumber_field.modelfields
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.FloatField(default=0.0)),
                ('description_box', tinymce.models.HTMLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('cycle', models.CharField(choices=[('MONTHLY', 'MONTHLY'), ('ANNUALLY', 'ANNUALLY')], default='MONTHLY', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=mt_utils.get_package_feature_image_path)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('type', models.CharField(blank=True, choices=[('STUDENT', 'STUDENT'), ('COACH', 'COACH')], max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('has_added_data', models.BooleanField(default=False)),
                ('has_added_payment_method', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=mt_utils.get_profile_image_path)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='accounts.coursepackage')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MockPackages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=255)),
                ('amount_text', models.CharField(max_length=255)),
                ('description_box', tinymce.models.HTMLField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to=mt_utils.get_package_feature_image_path)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('packages', models.ManyToManyField(blank=True, related_name='mocks', to='accounts.CoursePackage')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('type', models.CharField(choices=[('INSTRUCTOR', 'INSTRUCTOR'), ('CEO', 'CEO'), ('POSTER', 'POSTER'), ('MEMBER', 'MEMBER')], max_length=255)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=mt_utils.get_profile_image_path)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
