# Generated by Django 3.1.3 on 2020-12-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepackage',
            name='points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
