# Generated by Django 3.1.3 on 2020-11-28 15:31

from django.db import migrations, models
import mt_utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=mt_utils.get_profile_image_path),
        ),
    ]
