# Generated by Django 3.1.3 on 2020-12-22 18:10

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='details',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
