# Generated by Django 3.1.3 on 2020-11-29 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mt_utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_member_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('STUDENT', 'STUDENT'), ('COACH', 'COACH')], max_length=255)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=mt_utils.get_profile_image_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
