# Generated by Django 3.1.3 on 2021-01-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_member_small_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepackage',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
