# Generated by Django 3.1.3 on 2021-01-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210104_1720'),
        ('accounts', '0005_auto_20210104_1719'),
    ]

    operations = [
    ]
