# Generated by Django 3.1.3 on 2021-01-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20210104_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepackage',
            name='cycle',
            field=models.CharField(choices=[('MONTHLY', 'MONTHLY'), ('ANNUALLY', 'ANNUALLY'), ('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY')], default='MONTHLY', max_length=50),
        ),
    ]
