# Generated by Django 3.1.3 on 2020-12-04 18:58

from django.db import migrations, models
import mt_utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201202_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepackage',
            name='image',
            field=models.ImageField(null=True, upload_to=mt_utils.get_package_feature_image_path),
        ),
    ]
