# Generated by Django 3.1.3 on 2021-01-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210105_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockpackages',
            name='is_annually',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='mockpackages',
            name='is_monthly',
            field=models.BooleanField(null=True),
        ),
    ]
