# Generated by Django 3.1.3 on 2020-12-04 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_mockpackages'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockpackages',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mocks', to='accounts.coursepackage'),
        ),
    ]
