# Generated by Django 3.1.3 on 2021-01-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210116_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepackage',
            name='currency',
            field=models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='mockpackages',
            name='currency',
            field=models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD')], default='USD', max_length=3),
        ),
    ]
