# Generated by Django 3.1.3 on 2021-01-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210116_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.CharField(blank=True, choices=[('PLAYER', 'PLAYER'), ('COACH', 'COACH')], max_length=255, null=True),
        ),
    ]
