# Generated by Django 3.1.3 on 2020-12-04 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201204_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockpackages',
            name='package',
        ),
    ]
