# Generated by Django 3.1.3 on 2020-12-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_mockpackages_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockpackages',
            name='packages',
            field=models.ManyToManyField(blank=True, related_name='mocks', to='accounts.CoursePackage'),
        ),
    ]
