# Generated by Django 3.1.3 on 2020-12-06 02:32

from django.db import migrations, models
import mt_utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_mockpackages_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepackage',
            name='cycle',
            field=models.CharField(choices=[('MONTHLY', 'MONTHLY'), ('ANNUALLY', 'ANNUALLY')], default='MONTHLY', max_length=50),
        ),
        migrations.AlterField(
            model_name='coursepackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=mt_utils.get_package_feature_image_path),
        ),
    ]
