# Generated by Django 3.1.3 on 2020-12-09 22:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20201209_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepackage',
            name='description_box',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mockpackages',
            name='description_box',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
