# Generated by Django 3.1.3 on 2020-11-22 15:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('ticket', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('page_name', models.CharField(max_length=255)),
                ('data', models.TextField()),
            ],
        ),
    ]
