# Generated by Django 3.1.3 on 2020-12-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelogo',
            name='style',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
