# Generated by Django 3.1.3 on 2020-12-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0002_sitelogo_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
