# Generated by Django 3.1.3 on 2020-12-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0003_partner_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
