# Generated by Django 3.1.3 on 2020-12-22 14:18

from django.db import migrations, models
import mt_utils


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0004_faq_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='flyer_image',
            field=models.ImageField(null=True, upload_to=mt_utils.get_camp_image_path),
        ),
    ]
