# Generated by Django 3.1.3 on 2020-12-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0005_camp_flyer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
