# Generated by Django 3.1.3 on 2020-11-27 16:08

from django.db import migrations, models
import mt_utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0005_address_agreement_camp_campimage_contactnumber_email_privacypolicy_termandcondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=mt_utils.get_logo_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
