# Generated by Django 3.1.3 on 2020-11-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0006_sitelogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelogo',
            name='for_content',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
