# Generated by Django 3.1.3 on 2020-12-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0006_camp_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='camps', to='site_data.CampImage'),
        ),
    ]
