# Generated by Django 3.1.3 on 2020-12-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0007_auto_20201222_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
