# Generated by Django 3.1.3 on 2020-11-28 14:03

from django.db import migrations, models
import mt_utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0007_sitelogo_for_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.TextField()),
                ('link', models.URLField()),
                ('logo', models.ImageField(upload_to=mt_utils.get_logo_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
