# Generated by Django 3.1.3 on 2020-12-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0008_camp_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactedvisitor',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
