# Generated by Django 3.1.3 on 2020-11-28 14:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0008_sociallink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitedata',
            options={'verbose_name_plural': 'Site Content Data'},
        ),
        migrations.AlterField(
            model_name='camp',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='campimage',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='data',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='termandcondition',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
