# Generated by Django 3.1.3 on 2020-12-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0009_auto_20201223_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactedvisitor',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
