# Generated by Django 3.1.3 on 2020-11-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0009_auto_20201128_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_feature',
            field=models.BooleanField(default=False),
        ),
    ]
