# Generated by Django 3.1.3 on 2020-12-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0011_testimonial_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
