# Generated by Django 3.1.3 on 2020-12-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0012_testimonial_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
