# Generated by Django 3.1.3 on 2020-11-28 16:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0012_upcoming_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='footer',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=tinymce.models.HTMLField(verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub_title',
            field=tinymce.models.HTMLField(),
        ),
    ]
