# Generated by Django 3.1.3 on 2020-12-24 10:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0013_gallery_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
