# Generated by Django 3.1.3 on 2020-11-28 16:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0013_auto_20201128_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='footer',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub_title',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
