# Generated by Django 3.1.3 on 2020-12-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0014_agreement_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='termandcondition',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
