# Generated by Django 3.1.3 on 2020-12-24 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0015_auto_20201224_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='image',
        ),
    ]
