# Generated by Django 3.1.3 on 2020-11-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0015_auto_20201128_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
