# Generated by Django 3.1.3 on 2020-11-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0016_auto_20201128_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='post_comments', to='site_data.Thread'),
        ),
    ]
