# Generated by Django 3.1.3 on 2020-12-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0017_agreement_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
