# Generated by Django 3.1.3 on 2020-11-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
        ('site_data', '0018_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadreply',
            name='by',
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='post_comments', to='comment.Thread'),
        ),
        migrations.AlterField(
            model_name='question',
            name='comments',
            field=models.ManyToManyField(related_name='question_comments', to='comment.Thread'),
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
        migrations.DeleteModel(
            name='ThreadReply',
        ),
    ]
