# Generated by Django 3.1.3 on 2020-12-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0019_galleryvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryvideo',
            name='video_url',
        ),
        migrations.AddField(
            model_name='galleryvideo',
            name='youtube_video_id',
            field=models.CharField(default='92c3dX-AoXs', max_length=255),
            preserve_default=False,
        ),
    ]
