# Generated by Django 3.1.3 on 2022-05-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0021_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='cta',
            field=models.URLField(blank=True, null=True),
        ),
    ]
