MEMBER_TYPE_CHOICES = (
    ('INSTRUCTOR', 'INSTRUCTOR'),
    ('CEO', 'CEO'),
    ('POSTER', 'POSTER'),
    ('MEMBER', 'MEMBER')
)

USER_PROFILE_TYPE_CHOICES = (
    ('STUDENT', 'STUDENT'),
    ('COACH', 'COACH'),
)
