# Generated by Django 3.1.2 on 2020-10-25 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import email_client.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ein', models.PositiveBigIntegerField(auto_created=True, default=email_client.models.create_ein, editable=False)),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.EmailField(max_length=254)),
                ('text_body', models.TextField()),
                ('html_body', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
