# Generated by Django 3.1.2 on 2020-10-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_client', '0003_auto_20201025_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
