# Generated by Django 3.1.2 on 2020-10-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_client', '0004_email_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.TextField(),
        ),
    ]
