# Generated by Django 3.1.2 on 2020-10-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_client', '0005_auto_20201025_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='error_msg',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='status_code',
            field=models.PositiveSmallIntegerField(default=200),
        ),
    ]
