# Generated by Django 3.1.2 on 2020-10-25 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_client', '0007_auto_20201025_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='error_msg',
            new_name='error_message',
        ),
    ]
