# Generated by Django 3.1.3 on 2020-12-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='threadreply',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
